# .air.toml

     [build]
     bin = "bin/main" # output binary location
     cmd = "go build -o ./bin/main" # build command
     include_ext = ["go", "tpl", "tmpl", "html"] # file extensions to watch
     exclude_dir = ["assets", "tmp", "vendor"] # directories to exclude
     exclude_file = ["air.conf"] # files to exclude
     follow_symlink = true
     full_bin = "APP_ENV=dev APP_USER=air ./bin/main" # command to run the binary

     [log]
     level = "debug"